---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: helm-controller-yr-lab
  namespace: yr-demos-7wcpt
spec:
  addonRef:
    name: helm-controller
  clusters:
  - selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: yr-lab
